- name: Install Docker
  hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: Remove Docker and related packages
    apt:
      name: 
        - docker.io
        - docker-compose
        - docker-compose-v2
        - docker-doc
        - podman-docker
      state: absent
      autoremove: yes

  - name: Upgrade all apt packages
    apt:
      force_apt_get: yes
      upgrade: dist

  - name: Install required packages
    apt:
      pkg: 
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
      state: present
      update_cache: yes

  - name: Add Docker GPG key
    get_url:
      url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
      dest: /etc/apt/keyrings/docker.asc

  - name: Add Docker repository
    apt_repository:
      repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} stable"
      state: present

  - name: Install Docker packages
    apt:
      package: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present
      update_cache: yes

  - name: Add the user to the docker group
    user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: yes


