#!/bin/bash

message="$(cat $1)"
requiredPattern="^\[.*\]\[.*\] .*$"
if ! [[ $message =~ $requiredPattern ]];
then
    echo "-"
    echo "🚨 Commit message is not in correct format! 😕"
    echo "The commit message must have this format:"
    echo "[<feature name>][<author>]: <what was done>"
    echo "Example: [Authentication][Duy] add login button"
    echo "-"
    echo "Your commit message was:"
    echo $message
    echo "-"
    echo "For more information, check script in .husky/commit-msg"
    echo "-"
    exit 1
fi
