name: "Continuous Integration and Continuous Deployment"

on:
  push:
    branches:
      - main
      - dev
      - release

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_CLOUD_ORGANIZATION: "${{ secrets.TF_CLOUD_ORGANIZATION }}"
  TF_WORKSPACE: "${{ secrets.TF_WORKSPACE }}"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    needs: build
    if: github.ref == 'refs/heads/release'
    uses: ./.github/workflows/publish.yml
    secrets: inherit

  provision:
    needs: publish
    uses: ./.github/workflows/packer-build.yml
    secrets: inherit

  deploy:
    needs: provision
    uses: ./.github/workflows/terraform-apply.yml
    secrets: inherit
